### ISSUE TITLE
Metadata extraction

### ISSUE THREAD

**Issue by smathermather** [localdevices/ODMax#13]

**Comment by smathermather** [comment]
https://www.trekview.org/blog/2021/turn-360-video-into-timelapse-images-part-2/

**Comment by smathermather** [comment]
Hmm, we've got pyexiftool and this for parsing exif: https://pypi.org/project/piexif/

I suspect exiftool is the only comprehensive solution, but leaving piexif here just in case.

**Comment by ivangayton** [comment]
I've been using exifread to extract location from ebee photos
https://github.com/ivangayton/GDAL_scripts/blob/main/extract_location_from_exif.py

**Comment by smathermather** [comment]
exiftool reads the audio track to generate the GPX rather nicely, but this is not without challenges.

This is the step I am stuck on:
```
exiftool -datetimeoriginal="2020:09:06 17:37:22" 50/
exiftool -fileorder FileName -ext jpg '-datetimeoriginal+<0:0:$filesequence' 50/
exiftool -ext jpg -geotag GOPR0011_1599383304667.gpx "-Geotime<${DateTimeOriginal}Z" 50/
```

**Comment by smathermather** [comment]
Ah, this is useful:
https://guides.trekview.org/explorer/developer-docs/sequences/process/gopro-video-telemetry

**Comment by smathermather** [comment]
As is this:
https://github.com/trek-view/gopro-metadata

**Comment by smathermather** [comment]
I also attempted this dance:
```
exiftool -ext jpg -DateTimeOriginal="2020-09-06 07:37:22Z" -SubSecTimeOriginal="580" -SubSecDateTimeOriginal="2020-09-06T07:37:22.580Z" 50/

exiftool -fileorder FileName -ext jpg '-DateTimeOriginal+<0:0:$filesequence' '-SubSecDateTimeOriginal+<0:0:$filesequence' 50/
exiftool -ext jpg -Geotag GOPR0011_1599383304667.gpx "-Geotime<SubSecDateTimeOriginal" 50/
```

**Comment by hcwinsemius** [comment]
https://stackoverflow.com/questions/2566412/find-nearest-value-in-numpy-array

To ditch exiftool we can use `find_nearest` for searching the right time stamp for allocating geotags.

**Comment by hcwinsemius** [comment]
https://gist.github.com/c060604/8a51f8999be12fc2be498e9ca56adc72

For using `piexiv` to parse geolocations.
