### ISSUE TITLE
Overlap setting

### ISSUE THREAD

**Issue by hcwinsemius** [localdevices/ODMax#14]
Allow for overlap in the reprojected cube grids.
- [x] Modification of py360convert.utils.xyzcube to allow for more flexible xyz coordinates than -0.5...0.5 for the varying coordinates per cube face
- [x] CLI setting modification `--overlap` (ratio of face width, default to 0.1)
- [x] modify setup.py dependency to py360convert fork

**Comment by smathermather** [comment]
Also relevant: https://github.com/localdevices/py360convert/pull/1
