### ISSUE TITLE
CLI not working in Windows

### ISSUE THREAD

**Issue by hcwinsemius** [localdevices/ODMax#17]
When working on a Windows machine, the "script" property in setup.py does not work as expected. The ideal solution is to change the CLI to a click-based one. This will also give flexibility for future extensions, and options to color-code help functionalities.

**Comment by smathermather** [comment]
Fixed via: https://github.com/localdevices/ODMax/commit/758b6d05ed8fa0ee7f3832bda3793df005aea417
